"""Overview page: mirrors README.md Sec 3 "主要な発見". Tier 1 only --
static images already generated by scripts/generate_figures.py, no
recomputation on this page at all."""

from __future__ import annotations

from pathlib import Path

import streamlit as st

from dashboard.components import tier1_banner_text

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
FIGURES_DIR = REPO_ROOT / "reports" / "figures"

st.title("strategy-lab: 検証結果ダッシュボード")
st.info(tier1_banner_text())

st.header("Equity Curve比較（3戦略）")
st.image(str(FIGURES_DIR / "equity_curves_comparison.png"))
st.caption(
    "pairs_trading（AEP-FE）は狭い2セクタープールでの参考情報であり、全宇宙補正では統計的に有意でない"
    "（詳細はPairs Tradingページを参照）。"
)

st.header("多重検定問題（最もインパクトの大きい発見）")
st.image(str(FIGURES_DIR / "multiple_testing_bonferroni.png"))
st.caption(
    "同一の生p値が、検定族の定義（n_tests）次第で有意にも有意でないにもなる。"
    "詳細はPairs Tradingページ、strategies/pairs_trading/README.mdを参照。"
)

st.header("Walk-Forward / パラメータ感度分析")
st.image(str(FIGURES_DIR / "walk_forward_oos_sharpe.png"))
st.image(str(FIGURES_DIR / "sensitivity_grids.png"))

st.markdown(
    "各戦略の詳細（Tier 1の事前計算結果とTier 2のライブ探索）はサイドバーから遷移してください。"
    "既知の限界は「既知の限界」ページに一覧化しています。"
)
