"""Data-loading layer for the dashboard: Tier 1 precomputed results and
Tier 2 frozen price-panel snapshots, both committed under dashboard/data/
and generated by scripts/generate_dashboard_data.py.

Every loader is wrapped in st.cache_data so a page reload/rerun (e.g. a
slider move) never re-reads from disk. Nothing here ever calls yfinance
or DataLoader -- see scripts/generate_dashboard_data.py's module
docstring for why the dashboard deliberately does not fetch live data.

`data_dir` is an explicit parameter (defaulting to the real committed
directory) rather than a hidden module-level global read inside each
function: st.cache_data keys its cache on a function's ARGUMENTS, so a
zero-argument loader would cache its first result forever within a
process -- tests that point at a different (synthetic, tmp_path) data
directory need `data_dir` to actually participate in the cache key.
"""

from __future__ import annotations

import json
import os
import pickle
from dataclasses import dataclass
from datetime import date
from pathlib import Path

import pandas as pd
import streamlit as st

from strategies.pairs_trading.cointegration import PairCandidate

DEFAULT_DATA_DIR = Path(__file__).resolve().parent / "data"
DATA_DIR_ENV_VAR = "DASHBOARD_DATA_DIR"


def resolve_data_dir() -> Path:
    """DASHBOARD_DATA_DIR, read at page-execution time (not import time),
    lets tests point pages at a small synthetic fixture directory instead
    of the real committed snapshot -- see tests/dashboard/test_pages.py."""
    override = os.environ.get(DATA_DIR_ENV_VAR)
    return Path(override) if override else DEFAULT_DATA_DIR


@dataclass(frozen=True)
class WindowResultData:
    label: str
    oos_sharpe: float | None
    permutation_p: float | None


@dataclass(frozen=True)
class BonferroniScanData:
    n_tests: int
    survivors_before: int
    survivors_after: int
    label: str


@dataclass(frozen=True)
class Tier1Data:
    as_of: date
    pairs_trading_candidate: tuple[str, str]
    pairs_trading_walk_forward: list[WindowResultData]
    factor_momentum_walk_forward: list[WindowResultData]
    vol_arbitrage_walk_forward: list[WindowResultData]
    raw_p: float
    bonferroni_scans: list[BonferroniScanData]


@st.cache_data
def load_tier1_precomputed(data_dir: Path = DEFAULT_DATA_DIR) -> Tier1Data:
    with open(data_dir / "tier1_precomputed.json", encoding="utf-8") as f:
        raw = json.load(f)
    return Tier1Data(
        as_of=date.fromisoformat(raw["as_of"]),
        pairs_trading_candidate=tuple(raw["pairs_trading_candidate"]),
        pairs_trading_walk_forward=[WindowResultData(**w) for w in raw["pairs_trading_walk_forward"]],
        factor_momentum_walk_forward=[WindowResultData(**w) for w in raw["factor_momentum_walk_forward"]],
        vol_arbitrage_walk_forward=[WindowResultData(**w) for w in raw["vol_arbitrage_walk_forward"]],
        raw_p=raw["raw_p"],
        bonferroni_scans=[BonferroniScanData(**s) for s in raw["bonferroni_scans"]],
    )


@st.cache_data
def load_pairs_trading_snapshot(data_dir: Path = DEFAULT_DATA_DIR) -> tuple[pd.DataFrame, pd.DataFrame]:
    close = pd.read_parquet(data_dir / "snapshot_pairs_trading_close.parquet")
    open_ = pd.read_parquet(data_dir / "snapshot_pairs_trading_open.parquet")
    return close, open_


@st.cache_data
def load_pairs_trading_candidate(data_dir: Path = DEFAULT_DATA_DIR) -> PairCandidate:
    with open(data_dir / "snapshot_pairs_trading_candidate.pkl", "rb") as f:
        candidate: PairCandidate = pickle.load(f)
    return candidate


@st.cache_data
def load_vol_arbitrage_snapshot(data_dir: Path = DEFAULT_DATA_DIR) -> tuple[pd.DataFrame, pd.DataFrame]:
    close = pd.read_parquet(data_dir / "snapshot_vol_arbitrage_close.parquet")
    open_ = pd.read_parquet(data_dir / "snapshot_vol_arbitrage_open.parquet")
    return close, open_


@st.cache_data
def load_factor_momentum_snapshot(data_dir: Path = DEFAULT_DATA_DIR) -> tuple[pd.DataFrame, pd.DataFrame]:
    close = pd.read_parquet(data_dir / "snapshot_factor_momentum_close.parquet")
    open_ = pd.read_parquet(data_dir / "snapshot_factor_momentum_open.parquet")
    return close, open_
